### ISSUE TITLE
Need stemming and/or explicit cognate list

### ISSUE THREAD

**Issue by DavidMertz** [chrismattmann/politics-hacking#1]
This only detects the literal string 'russia' and not e.g. 'russian', 'russophile', 'russophone', 'soviet', 'moscow', 'kremlin', 'apparatchik', 'Россия'.  Ideally would probably be to use the Porter Stemmer (in NLTK) and a larger synonym list.

**Comment by chrismattmann** [comment]
Yep good one. It will pick up "russian" b/c russia is in it, but not russophile and russophone and those other good ones. I just did a quick hack in an hour, bruh. 👍 But if I get more time, will bust out NLTK wizardry. Or some nice dude could do it for me ;)

**Comment by DavidMertz** [comment]
Maybe I'll submit a PR.

**Comment by DavidMertz** [comment]
I'd like to push a branch but do not have permissions.

**Comment by chrismattmann** [comment]
@DavidMertz just sent you an invite

**Comment by chrismattmann** [comment]
@DavidMertz and his start in https://github.com/chrismattmann/politics-hacking/commit/63be1ca2839ab8c267b7c554fa879c7a4cedbccc is enough for me to close this for now.
