### ISSUE TITLE
Filtering stop words irrelevant to raw count

### ISSUE THREAD

**Issue by DavidMertz** [chrismattmann/politics-hacking#2]
If you were to give a density ratio filtering stopwords would be relevant.  However, for a raw count this devotes about half the work to something that has no effect on the calculation.

E.g. drop these lines:

```python
stop_words = frozenset(requests.get('https://raw.githubusercontent.com/stanfordnlp/CoreNLP/master/data/edu/stanford/nlp/patterns/surface/stopwords.txt').content.split())
...
    finalWords = [w for w in words if w not in stop_words] #remove stop words       
```

**Comment by chrismattmann** [comment]
good point - I was working on something where I was originally processing the count dictionary, but then decided screw it I didn't need to be so fancy. So I didn't remove this part.
